stages:
  - build
  - test
  - deploy

image: busybox:latest

before_script:
  - echo "Before script section"
  - echo "For example you might run an update here or install a build dependency"
  - echo "Or perhaps you might print out some debugging details"

after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"

build1:
  stage: build
  script:
    - echo "Build files"
    - echo "<html><head><title>404</title></head><body><h1>404</h1>Page not found!</body></html>" > 404.txt
    - echo "<html><head><title>Welcome!</title></head><body><h1>Welcome!</h1>Success! The server block is working!</body></html>" > index.txt
  artifacts:
    paths:
      - 404.txt
      - index.txt
    expire_in: 1 week

test1:
  stage: test
  script:
    - echo "Check 404.txt file"
    - grep "404" 404.txt

test2:
  stage: test
  script:
    - echo "Check index.txt file"
    - grep "Welcome" index.txt

deploy1:
  stage: deploy
  script:
    - echo "Do your deploy here"

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp index.txt public/index.html
    - cp 404.txt public/404.html
  artifacts:
    paths:
      - public
  only:
    - main