image: docker:19.03.12

services:
  - docker:19.03.12-dind

stages:
  - build
  - test
  - deploy

variables:
  IMAGE_TAG: $CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA
  DOCKER_DRIVER: overlay
  DOCKER_HOST: tcp://docker:2375 
  DOCKER_TLS_CERTDIR: ""

before_script:
  - docker login -u $GITLAB_CI_USER -p $GITLAB_CI_PASSWORD $CI_REGISTRY

build image:
  stage: build
  script:
    - echo $GITLAB_CI_USER $GITLAB_CI_PASSWORD $CI_REGISTRY $CI_REGISTRY_IMAGE:$IMAGE_TAG
    - docker build -t $CI_REGISTRY_IMAGE:$IMAGE_TAG .
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG

test image:
  stage: test 
  script:
    - docker run -d --name test $CI_REGISTRY_IMAGE:$IMAGE_TAG
    - docker ps

deploy image:
  stage: deploy
  script:
    - echo "Do your deploy here"